//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1._2Prakt
{
    using System;
    using System.Collections.Generic;
    
    public partial class BULDING_OBJECT
    {
        public int ID_OBJECT { get; set; }
        public int WORKER_ID { get; set; }
        public int MATERIALS_ID { get; set; }
        public int POSTAVSHIK_ID { get; set; }
    
        public virtual MATERIALS MATERIALS { get; set; }
        public virtual POSTAVSHIK POSTAVSHIK { get; set; }
        public virtual workers workers { get; set; }
    }
}
