//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1._2Prakt
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class stroikontorkaEntities : DbContext
    {
        public stroikontorkaEntities()
            : base("name=stroikontorkaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BULDING_OBJECT> BULDING_OBJECT { get; set; }
        public virtual DbSet<MATERIALS> MATERIALS { get; set; }
        public virtual DbSet<POSTAVSHIK> POSTAVSHIK { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<workers> workers { get; set; }
    }
}
